#!/bin/bash
set -euo pipefail
# Add a `core` user with sudo, and set it up for
# automatic login.  Note that unlike the existing Fedora
# Live images, we don't remove the password.  That's a bad
# idea in case someone enables SSH (and yes the default
# ssh config also prevents this, but still).

# On the main installed system, we don't want to do this.
if grep -q ignition.platform.id=metal /proc/cmdline && \
   ! [ -f /run/ostree-live ]; then
   exit 0
fi

useradd core -G wheel
# Rely on PermitEmptyPasswords=no for ssh.  That doesn't stop
# other local accounts from using `su` but we ignore that for now.
# What we really want is something like "skip authentication on
# local console".
passwd -d core
runuser -u core -- /bin/sh -c 'mkdir -p ~/.config && touch ~/.config/gnome-initial-setup-done'
echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel-nopasswd
cat >> /etc/gdm/custom.conf << EOF
[daemon]
AutomaticLoginEnable=True
AutomaticLogin=core
EOF
